name: publish to pypi

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: |
          make build
      - name: Publish package
        run: |
          poetry publish --username "__token__" --password "${{ secrets.PYPI_API_TOKEN }}"
